import Foundation

struct Town: Identifiable, Codable, Equatable {
    var id: UUID
    var name: String
    var resources: ResourceWallet
    var buildings: [BuildingInstance]
    var biomeLayout: TownBiomeLayout
    /// Opaque server-assigned player ID (human or AI) that owns this island.
    /// There are no factions: every rule is an ownership comparison.
    var ownerID: String
    var isDuskara: Bool
    var armyStrength: Int
    var soldierRoster: SoldierRoster

    init(
        id: UUID = UUID(),
        name: String,
        resources: ResourceWallet = ResourceWallet(),
        buildings: [BuildingInstance] = [],
        biomeLayout: TownBiomeLayout,
        ownerID: String,
        isDuskara: Bool = false,
        armyStrength: Int = 0,
        soldierRoster: SoldierRoster = SoldierRoster()
    ) {
        self.id = id
        self.name = name
        self.resources = resources
        self.buildings = buildings
        self.biomeLayout = biomeLayout
        self.ownerID = ownerID
        self.isDuskara = isDuskara
        self.armyStrength = armyStrength
        self.soldierRoster = soldierRoster
    }

    var forestSideCount: Int {
        biomeLayout.sides.values.filter { $0 == .forest }.count
    }

    var mountainSideCount: Int {
        biomeLayout.sides.values.filter { $0 == .mountain }.count
    }

    var specializationSummary: String {
        if forestSideCount >= 3 { return "Wood-rich settlement" }
        if mountainSideCount >= 3 { return "Coal-rich settlement" }
        return "Balanced settlement"
    }
}

struct WorldTownNode: Identifiable, Codable, Equatable {
    var id: UUID { townID }
    var townID: UUID
    var x: Double
    var y: Double
}

struct TownConnection: Identifiable, Codable, Equatable, Hashable {
    var from: UUID
    var to: UUID

    var id: String { "\(from.uuidString)-\(to.uuidString)" }

    func contains(_ townID: UUID) -> Bool {
        from == townID || to == townID
    }

    func connects(_ lhs: UUID, _ rhs: UUID) -> Bool {
        (from == lhs && to == rhs) || (from == rhs && to == lhs)
    }
}

/// Local working model assembled from the replication boundary:
/// WorldDefinition (immutable world) + MatchState (mutable match).
/// Presentation-only values such as the active town live in the view model,
/// never here.
/// One rolling offer from a neighboring free city, generated by the rules
/// layer as a seeded per-day event (never from wall-clock randomness).
struct TownTradeOffer: Codable, Equatable, Identifiable {
    /// Deterministic: "trade-<day>-<townID>".
    var id: String
    var townID: UUID
    /// Server-assigned player ID of the trading partner. Clients never
    /// fabricate partners; they target IDs the authority handed out.
    var partnerPlayerID: String
    var wants: [ResourceKind: Int]
    var gives: [ResourceKind: Int]
    /// The offer disappears when the day reaches this value.
    var expiresOnDay: Int
}

struct GameState: Codable, Equatable {
    var day: Int
    /// Server timestamp (ms) when the current day started. Display and
    /// day-advance decisions derive from this plus ServerClock; the client
    /// never accumulates its own elapsed counter.
    var dayStartServerMillis: Int64
    var towns: [Town]
    var worldNodes: [WorldTownNode]
    var connections: [TownConnection]
    var world: WorldMapState
    var territory: TerritoryState
    /// Durable match lifecycle, owned by the rules layer.
    var status: MatchStatus
    /// Server-assigned IDs of the human players, in join order. Every other
    /// owner ID in `towns` belongs to a server-owned AI player.
    var humanPlayerIDs: [String]
    /// Set when status becomes .finished. Nil on a finished match means no
    /// human won (single-player defeat).
    var winnerPlayerID: String?
    var newsEvents: [NewsEvent]
    /// Live seeded trade offers, one at most per town.
    var tradeOffers: [TownTradeOffer]
    /// Monotonic counter behind deterministic entity-ID minting.
    var entityCounter: Int

    init(
        day: Int,
        dayStartServerMillis: Int64 = 0,
        towns: [Town],
        worldNodes: [WorldTownNode],
        connections: [TownConnection],
        world: WorldMapState = .empty,
        territory: TerritoryState = .empty,
        status: MatchStatus = .active,
        humanPlayerIDs: [String],
        winnerPlayerID: String? = nil,
        newsEvents: [NewsEvent] = [],
        tradeOffers: [TownTradeOffer] = [],
        entityCounter: Int = 0
    ) {
        self.day = day
        self.dayStartServerMillis = dayStartServerMillis
        self.towns = towns
        self.worldNodes = worldNodes
        self.connections = connections
        self.world = world
        self.territory = territory
        self.status = status
        self.humanPlayerIDs = humanPlayerIDs
        self.winnerPlayerID = winnerPlayerID
        self.newsEvents = newsEvents
        self.tradeOffers = tradeOffers
        self.entityCounter = entityCounter
    }
}

enum GamePhase: Equatable {
    case setup
    case town
    case victory
}
